// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace PhamDuyQuang785.Migrations
{
    [DbContext(typeof(CompanyPDQ785Context))]
    [Migration("20211215070906_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("PhamDuyQuang785.Models.CompanyPDQ785", b =>
                {
                    b.Property<string>("CompanyID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyID");

                    b.ToTable("CompanyPDQ785");
                });

            modelBuilder.Entity("PhamDuyQuang785.Models.PDQ0785", b =>
                {
                    b.Property<string>("PDQid")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PDQName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PDQgender")
                        .HasColumnType("INTEGER");

                    b.HasKey("PDQid");

                    b.ToTable("PDQ0785");
                });
#pragma warning restore 612, 618
        }
    }
}
